Title
========================================================

This is how I learn TSA

```{r}

```

```{r}
library(TSA)
win.graph(width= 4.875, height= 2.5, pointsize= 8)
data(larain);plot(larain, ylab= 'Inches', xlab='Year', type='o');title(main = "洛杉矶年降水量时间序列图")
```
```{r}
library(TSA)
win.graph(width= 4.875, height= 2.5, pointsize= 8)
data(larain);plot(larain, ylab= 'Inches', xlab='Year', type='o');title(main = "洛杉矶年降水量时间序列图")
plot
```
```{r fig.width=7, fig.height=6}
plot(cars)
```

```{r}
data(rwalk)
modell=lm(rwalk~time(rwalk))
summary(modell)
win.graph(width= 4.875, height= 2.5, pointsize= 8)
plot(rwalk, type='o', ylab='y')
abline(modell)

data(tempdub)
month.=season(tempdub)
model2=lm(tempdub~month.-1)
summary(model2)

har. = harmonic(tempdub,1)
model4 = lm(tempdub~har.)
summary(model4)
win.graph(width= 4.875, height= 2.5, pointsize= 8)
plot(ts(fitted(model4),freq=12,star=c(1964,1)),ylab='Temperature',type="l",
     ylim=range(c(fitted(model4),tempdub)));
points(tempdub)
```

